DRUMKIT = {
    'clap': 'samples/DRUMKIT/clap.wav',
    'clave': 'samples/DRUMKIT/clave.wav',
    'cowbell': 'samples/DRUMKIT/cowbell.wav',
    'hihat-closed': 'samples/DRUMKIT/hihat-closed.wav',
    'kick': 'samples/DRUMKIT/kick.wav',
    'rim': 'samples/DRUMKIT/rim.wav',
    'tamb': 'samples/DRUMKIT/tamb.wav',
}

SM808 = {
    'clap': 'samples/808/clap.wav',
    'clave': 'samples/808/clave.wav',
    'congahi': 'samples/808/congahi.wav',
    'congalo': 'samples/808/congalo.wav',
    'congamid': 'samples/808/congamid.wav',
    'cowbell': 'samples/808/cowbell.wav',
    'cymbal': 'samples/808/cymbal.wav',
    'hhclosed': 'samples/808/hhclosed.wav',
    'hhopen': 'samples/808/hhopen.wav',
    'kickrr': 'samples/808/kickrr.wav',
    'kickrr2': 'samples/808/kickrr2.wav',
    'kickrr3': 'samples/808/kickrr3.wav',
    'kick': 'samples/808/kick.wav',
    'kick2': 'samples/808/kick2.wav',
    'kick3': 'samples/808/kick3.wav',
    'maracas': 'samples/808/maracas.wav',
    'rimshot': 'samples/808/rimshot.wav',
    'snare': 'samples/808/snare.wav',
    'snare2': 'samples/808/snare2.wav',
    'snare3': 'samples/808/snare3.wav',
    'tomhi': 'samples/808/tomhi.wav',
    'tomlo': 'samples/808/tomlo.wav',
    'tommid': 'samples/808/tommid.wav',
}